spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root

---
api:
  security:
    jwt:
      secret: ${JWT_SECRET:secret}
      time-to-live: ${JWT_TTL:60}

